name: Cypress Tests

on: [push]

jobs:
  cypress-electron-testes:
    runs-on: ubuntu-latest
    steps: 
     - name: Get code
       uses: actions/checkout@v3.5.3
       
     - name: Install dependencies
       run: npm install
       
     - name: run E2E tests
       run: npm cypress run 
      
