name: Cypress Tests

on: 
  workflow_dispatch:
    inputs:
      cli:
        description: Run by cypress command line
        default: npx cypress run

jobs:
  cypress-electron-testes:
    runs-on: ubuntu-latest
    steps: 
     - name: Get code
       uses: actions/checkout@v3.5.3
       
     - name: Install dependencies
       run: npm install
       
     - name: run E2E tests
       run: ${{ github.event.inputs.cli }}
      
